-- Figma Comment Pilot MCP Server — Database Schema
-- Version: 3.1

-- 1. Comments table (core data, one row per comment, logically linked by threads)
CREATE TABLE IF NOT EXISTS comments (
    id TEXT PRIMARY KEY,                -- Figma Comment ID
    file_key TEXT NOT NULL,
    parent_id TEXT,                     -- NULL for root comments
    root_id TEXT,                       -- Denormalized: root comment ID (equals id if root)
    message_text TEXT NOT NULL,         -- Original comment content
    author_id TEXT NOT NULL,            -- User ID (used for bot detection)
    author_handle TEXT,                 -- User display name
    created_at TEXT NOT NULL,           -- ISO 8601
    updated_at TEXT,                    -- Figma-side last update time
    deleted_at TEXT,                    -- Soft delete marker
    reactions_json TEXT,                -- JSON Array: [{"emoji":"👀","user_id":"..."}]
    remote_status_emoji TEXT,           -- Current effective status emoji from Figma
    local_status TEXT NOT NULL DEFAULT 'OPEN',  -- OPEN | PENDING | DONE | WONTFIX
    reply_posted_by_ai INTEGER NOT NULL DEFAULT 0  -- 1 if generated by this system
);

CREATE INDEX IF NOT EXISTS idx_comments_file_root ON comments(file_key, root_id);
CREATE INDEX IF NOT EXISTS idx_comments_status ON comments(local_status);
CREATE INDEX IF NOT EXISTS idx_comments_file_key ON comments(file_key);

-- 2. Operations outbox (idempotency & retry)
CREATE TABLE IF NOT EXISTS operations (
    op_id TEXT PRIMARY KEY,             -- UUID v4
    idempotency_key TEXT NOT NULL UNIQUE,  -- SHA256(file+root+action+content+agent)
    file_key TEXT NOT NULL,
    op_type TEXT NOT NULL,              -- REPLY | ADD_REACTION | REMOVE_REACTION | DELETE_COMMENT
    payload_json TEXT NOT NULL,         -- JSON: API request parameters
    state TEXT NOT NULL DEFAULT 'PENDING',  -- PENDING | PROCESSING | CONFIRMED | FAILED
    retry_count INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    figma_response_id TEXT,             -- Created comment ID from Figma response
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_operations_state ON operations(state);
CREATE INDEX IF NOT EXISTS idx_operations_file_key ON operations(file_key);

-- 3. Sync state (per-file sync metadata)
CREATE TABLE IF NOT EXISTS sync_state (
    file_key TEXT PRIMARY KEY,
    last_full_sync_at TEXT,
    last_event_id TEXT,                 -- Webhook cursor (future use)
    bot_user_id TEXT,                   -- Bot's Figma User ID for self-detection
    sync_config_json TEXT               -- JSON: {"ignored_users": [...]}
);

-- 4. Config (key-value store for tokens, settings)
CREATE TABLE IF NOT EXISTS config (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
